services:
  skeleton:
    image: skeleton
    build:
      context: .
      dockerfile: Dockerfile
  skeleton-database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: skeleton-database
    hostname: mssql-db
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'Passw0rd'
      MSSQL_DATA_DIR: /var/opt/mssql/data
      MSSQL_PID: 'Developer'
      MSSQL_TCP_PORT: 1433
    ports:
      - "1433:1433"
#    volumes:
#      - ./data:/var/opt/mssql/data
#      - ./log:/var/opt/mssql/log
#      - ./secrets:/var/opt/mssql/secrets
